const curso = require("./curso");
const estudantes = require('./estudantes');
const Aluno = require("./aluno");
let aluno6 = new Aluno("Juliana", 5, [7, 8.2, 9.0]);

console.log("                                              ")
console.log("Lista de alunos importados do módulo estudantes.js")
console.log("--------------------------------------------------")
console.log("                                              ")
console.log(estudantes)
console.log("                                              ")
console.log("Média das notas de cada aluno")
console.log("----------------------------------------------")
console.log(`${estudantes[0].nome}: ${estudantes[0].calcularMedia()}`)
console.log(`${estudantes[1].nome}: ${estudantes[1].calcularMedia()}`)
console.log(`${estudantes[2].nome}: ${estudantes[2].calcularMedia()}`)
console.log(`${estudantes[3].nome}: ${estudantes[3].calcularMedia()}`)
console.log(`${estudantes[4].nome}: ${estudantes[4].calcularMedia()}`)
console.log("                                              ")
console.log("Número de faltas de cada aluno")
console.log("----------------------------------------------")
console.log(`${estudantes[0].nome}: ${estudantes[0].numeroFaltas}`)
console.log(`${estudantes[1].nome}: ${estudantes[1].numeroFaltas}`)
console.log(`${estudantes[2].nome}: ${estudantes[2].numeroFaltas}`)
console.log(`${estudantes[3].nome}: ${estudantes[3].numeroFaltas}`)
console.log(`${estudantes[4].nome}: ${estudantes[4].numeroFaltas}`)
console.log("                                              ")
console.log("Objeto curso")
console.log("----------------------------------------------")
console.log(curso)
console.log("                                              ")
console.log("Adicionar novo aluno na lista")
console.log("----------------------------------------------")
console.log("ANTES:")
console.log(curso.listaEstudantes)
curso.addAluno(aluno6)
console.log("                                              ")
console.log("DEPOIS:")
console.log(curso.listaEstudantes)
console.log("                                              ")
console.log("Situação dos alunos")
console.log("----------------------------------------------")
curso.listaSituacao(curso.listaEstudantes)
console.log("                                              ")